# Generated by Django 4.2.1 on 2023-06-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="note_image",),
        migrations.AddField(
            model_name="note",
            name="password",
            field=models.CharField(
                blank=True, help_text="Optional Password", max_length=128
            ),
        ),
    ]
