# Generated by Django 4.1.7 on 2023-06-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Enter a course name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Optional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='common.course'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_image',
            field=models.ImageField(upload_to='notes/images/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='private_code',
            field=models.PositiveIntegerField(blank=True, help_text='Optional edit and deletion access.', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='share_code',
            field=models.PositiveIntegerField(blank=True, help_text='Optional view access restriction.', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(help_text='Atleast one tag required', related_name='notes', to='common.tag'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Required', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='week',
            field=models.PositiveIntegerField(blank=True, help_text='Optional', null=True),
        ),
    ]
