# Generated by Django 4.2.1 on 2023-06-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_note_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Enter tags seperated by commas.",
                null=True,
                related_name="notes",
                to="common.tag",
            ),
        ),
    ]
