# Generated by Django 4.2.1 on 2023-06-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="common.comment",
            ),
        ),
    ]
