# Generated by Django 4.2.1 on 2023-06-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_note_comments"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="comments",),
        migrations.AddField(
            model_name="comment",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="common.note",
            ),
        ),
    ]
