# Generated by Django 4.2.1 on 2023-06-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_remove_note_comments_comment_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="comments", new_name="note",
        ),
    ]
